### ISSUE TITLE
Impossible to display help

### ISSUE THREAD

**Issue by marmotz** [jubianchi/atoum.js#1]
```
./node_modules/atoum.js/bin/atoum -h
[TypeError] Converting circular structure to JSON
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at /media/data/dev/LSDManager/node_modules/atoum.js/node_modules/optimist/index.js:253:43
    at Array.forEach (native)
    at Object.Argv.self.help (/media/data/dev/LSDManager/node_modules/atoum.js/node_modules/optimist/index.js:218:14)
    at Object.Argv.self.showHelp (/media/data/dev/LSDManager/node_modules/atoum.js/node_modules/optimist/index.js:180:17)
    at fail (/media/data/dev/LSDManager/node_modules/atoum.js/node_modules/optimist/index.js:115:14)
    at /media/data/dev/LSDManager/node_modules/atoum.js/node_modules/optimist/index.js:312:17
    at Array.forEach (native)
    at parseArgs (/media/data/dev/LSDManager/node_modules/atoum.js/node_modules/optimist/index.js:305:16)
    at Object.Argv.Object.defineProperty.get [as argv] (/media/data/dev/LSDManager/node_modules/atoum.js/node_modules/optimist/index.js:282:36)
```

**Comment by jubianchi** [comment]
Weird!

This only happens when running atoum.js from the node_modules directory.
I'll try to find why...
